- hosts: localhost
  become: true
  tasks:
  - name: Install Python packages with apt
    apt: name={{item}}
    with_items:
      - build-essential
      - python3-dev
      - python3-pip
      - python3-virtualenv
  - name: Install Python packages with pip
    pip: pipenv
    extra_args: --user
    environment:
      PATH="$HOME/.local/bin:$PATH"

