- hosts: localhost
  become: true
  tasks:
    - name: Install Python packages with apt
      apt: name={{item}}
      loop:
        - build-essential
        - python3-dev
        - python3-pip
        - python3-virtualenv

    - name: Install Python packages with pip
      pip:
        name: pipenv
        executable: pip3
        extra_args: --user

